name: Brancher CICD

on: [push, pull_request]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install
      env:
        FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
    - name: Set up .npmrc
      run: echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
            echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_TOKEN }}" >> .npmrc

    - name: Run ESLint
      run: npm run lint
